name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_PAT: ${{ secrets.DOCKER_PAT }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'npm'

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: abdullah656
        password: ${{ secrets.DOCKER_PAT }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Test Auth Service
      working-directory: ./auth-service
      run: |
        npm ci
        npm test || true
        docker build -t abdullah656/auth-service:latest .
        docker push abdullah656/auth-service:latest

    - name: Build and Test Blog Service
      working-directory: ./blog-service
      run: |
        npm ci
        npm test || true
        docker build -t abdullah656/blog-service:latest .
        docker push abdullah656/blog-service:latest

    - name: Build and Test Comment Service
      working-directory: ./comment-service
      run: |
        npm ci
        npm test || true
        docker build -t abdullah656/comment-service:latest .
        docker push abdullah656/comment-service:latest

    - name: Build and Test Profile Service
      working-directory: ./profile-service
      run: |
        npm ci
        npm test || true
        docker build -t abdullah656/profile-service:latest .
        docker push abdullah656/profile-service:latest

    - name: Build and Test API Gateway
      working-directory: ./api-gateway
      run: |
        npm ci
        npm test || true
        docker build -t abdullah656/api-gateway:latest .
        docker push abdullah656/api-gateway:latest

    - name: Build and Push Docker Compose
      if: github.ref == 'refs/heads/main'
      run: |
        docker-compose build
        docker-compose push

    - name: Deploy Services
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deployment would happen here"
        # Add actual deployment steps based on your hosting platform
